feature: Run from lenses in local terminal
scalameta/metals-vscode pull request #1199
Opened 2022-10-24 16:43 UTC by tgodzik

![metals-sample-1666629739089](https://user-images.githubusercontent.com/3807253/197580145-e0786f27-f044-436e-a70e-ab47c35f10ab.gif)

2022-10-24 16:46 UTC, tgodzik commented
@kpodsiad what do you think? We can also generate lenses with run command and change the data that is being given, but that would not be that much gain and I think having the environment commands in metals server allows us for more flexibility.

2022-10-25 20:17 UTC, kpodsiad reviewed
It look promising, however I'll wait witch suggestions until we decide what should be done at server side.

2022-10-27 19:37 UTC, tgodzik commented on src/scalaDebugger.ts
> +      return start(debugConfiguration.noDebug, args).then(() => {
Turns out that debugConfiguration contains the noDebug flag as a undeclared field. This is useful when running with F5 (Run without debugging)

2022-10-27 19:37 UTC, tgodzik commented on src/scalaDebugger.ts
> +function isScalaRunMain(object: any): object is ScalaRunMain {
I am not super sure about this one, but seems to do the job :sweat_smile:

2022-11-03 18:30 UTC, kpodsiad requested changes
I left a couple of suggestions

2022-11-03 18:32 UTC, kpodsiad commented on src/testExplorer/types.ts
> +export type ScalaRunMain = OldScalaRunMain | ExtendedScalaRunMain;
Probably `ScalaTestSuites` and `ScalaTestSuiteSelection` should be moved also. Knowing how much you dislike typescipt, I could do those in separate PR ;)

2022-11-03 19:34 UTC, tgodzik commented on src/testExplorer/types.ts
> +export type ScalaRunMain = OldScalaRunMain | ExtendedScalaRunMain;
I don't dislike it, I am just not very good at it :sweat_smile:

2022-11-04 15:54 UTC, tgodzik commented on src/scalaDebugger.ts
> +}
Thanks done!

2022-11-04 15:54 UTC, tgodzik commented on src/scalaDebugger.ts
>  ): Promise<boolean> {
Done!

2022-11-04 15:54 UTC, tgodzik commented on src/scalaDebugger.ts
> +export async function debug(
Done!

2022-11-04 15:54 UTC, tgodzik commented on src/scalaDebugger.ts
Updated

2022-11-04 15:55 UTC, tgodzik commented on src/testExplorer/types.ts
> +export type ScalaRunMain = OldScalaRunMain | ExtendedScalaRunMain;
Ok, moved and everything seems to work fine. :sweat_smile:

2022-11-04 16:08 UTC, kpodsiad approved these changes
LGTM

2022-11-04 16:15 UTC, merged