improvement: New inlay hints options
scalameta/metals-vscode pull request #1475
Opened 2024-03-20 08:58 UTC by jkciesluk

connected to https://github.com/scalameta/metals/pull/6236

2024-03-22 11:02 UTC, tgodzik requested changes

2024-03-22 11:02 UTC, tgodzik commented on packages/metals-vscode/package.json
> +        "command": "metals.toggle-type-parameters",
Could we try to avoid rename the methods, it might break for people if they have shortcuts set up.

2024-03-22 20:25 UTC, jkciesluk commented on packages/metals-vscode/package.json
> +        "metals.inlayHints.inferredTypes.enable": {
We don't need it, but this is how other languages do it (TypeScript, Rust, C++)

2024-03-25 08:34 UTC, tgodzik commented on packages/metals-vscode/package.json
> +        "metals.inlayHints.inferredTypes.enable": {
Ok, we can leave it then, though would be great to know the reason why they do it so

2024-03-27 19:18 UTC, tgodzik approved these changes
LGTM! When the PR in Metals is merged let's also bump snapshot version

2024-04-15 09:27 UTC, tgodzik approved these changes

2024-04-15 09:27 UTC, merged