Add show TASTy command
scalameta/metals-vscode pull request #655
Opened 2021-08-24 07:38 UTC by kpodsiad

Changes required by https://github.com/scalameta/metals/pull/3063

2021-09-15 11:46 UTC, tgodzik requested changes
Looks good! Just a few smaller issues and you need to rebase.

2021-09-15 11:46 UTC, tgodzik commented on src/extension.ts
> +      } catch (err: any) {
This should not be needed:
```suggestion
      } catch (err) {
```

2021-09-15 11:46 UTC, tgodzik commented on package.json
> +}
Please run `yarn format`

2021-09-16 08:47 UTC, tgodzik approved these changes
LGTM! Let's wait for the next release.

2021-09-16 09:15 UTC, gabro approved these changes

2021-09-16 17:02 UTC, merged