Add `Start Metals` button
scalameta/metals-vscode pull request #814
Opened 2022-01-07 16:04 UTC by kpodsiad

2022-01-07 18:31 UTC, tgodzik approved these changes
LGTM!

2022-01-07 18:32 UTC, tgodzik requested changes
Actually, maybe let's make it simpler?

2022-01-07 18:32 UTC, tgodzik commented on package.json
> +        "contents": "No Scala project found. Create a new one or start Metals manually.\n[New Scala project](command:metals.new-scala-project)\n[Start Metals server](command:metals.start-server)",
```suggestion
        "contents": "No Scala project found. Create a new one or start Metals manually.\n[New Scala project](command:metals.new-scala-project)\n[Start Metals](command:metals.start-server)",
```

2022-01-07 18:49 UTC, tgodzik approved these changes
Thanks!

2022-01-08 11:52 UTC, Arthurm1 approved these changes
Works a treat - thanks @kpodsiad

2022-01-08 16:19 UTC, merged