refactor: store test's metadata directly in test
scalameta/metals-vscode pull request #921
Opened 2022-03-21 08:01 UTC by kpodsiad

Javascript is a dynamic language so it's possible to extend object and classes with new fields.

2022-03-21 08:17 UTC, kpodsiad reviewed
As I said, Javascript is dynamic and it allows to add the new fields to an existing object. I used this property to get rid off creating and keeping detached metadata per every test item. Instead, this information can be stored directly in the test item object.

In my opinion, it's a better approach and it reduces the number of unnecessary ifs (null & undefined guarding)

2022-03-21 08:17 UTC, kpodsiad commented on src/testExplorer/util.ts
> +export function refineTestItem(test: vscode.TestItem, kind: "testcase", targetUri: TargetUri, targetName: TargetName, parent: vscode.TestItem): TestCaseMetalsTestItem;
so in other words, you cannot call `refine` without parent if passed kind indicates that parent has to be present

2022-03-21 15:47 UTC, tgodzik requested changes
Great work! I have some minor comments.

2022-03-21 15:47 UTC, tgodzik commented on src/testExplorer/util.ts
> +  const casted = test as MetalsTestItem;
```suggestion
  const cast = test as MetalsTestItem;
```
I think it's `cast -> cast -> cast`

2022-03-21 15:47 UTC, tgodzik commented on src/testExplorer/util.ts
> +export function refineTestItem(test: vscode.TestItem, kind: "testcase", targetUri: TargetUri, targetName: TargetName, parent: vscode.TestItem): TestCaseMetalsTestItem;
Shouldn't this be an actual class with a constructor? It could all have `def toMetalsItem`

2022-03-22 10:21 UTC, kpodsiad commented
@tgodzik I added some comments to the overloaded function. Do you still find it confusing?

2022-03-22 12:41 UTC, tgodzik commented on src/testExplorer/util.ts
> +export function refineTestItem(test: vscode.TestItem, kind: "testcase", targetUri: TargetUri, targetName: TargetName, parent: vscode.TestItem): TestCaseMetalsTestItem;
Ach, I think I understand what is happening now :S and I feel it's pretty evil :sweat_smile:

2022-03-22 12:42 UTC, tgodzik approved these changes
LGTM

2022-04-01 07:23 UTC, merged